---
# Sometimes it seems $HOSTNAME isn't set...
- name: Get current hostname
  command:
    cmd: cat /etc/hostname
  register: current_hostname

- name: Setup hostname
  block:
  - name: Fix hosts file
    lineinfile:
      path: /etc/hosts
      regexp: '^127\.0\.1\.1'
      line: "127.0.1.1 {{ hostname }}"
      owner: root
      group: root
      mode: '0644'

  - name: Set hostname
    hostname:
      name: "{{ hostname }}"
  
  when: current_hostname.stdout != hostname
