---
- name: Get Microsoft package key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc

- name: Add Microsoft Visual Studio Code repo
  apt_repository:
    repo: deb https://packages.microsoft.com/repos/code stable main
    filename: microsoft-vscode
    state: present

- name: Install Microsoft Visual Studio Code
  apt:
    name: code
    update_cache: yes
    state: latest
